/* Messenger */

export const REQUESTED_INITIALIZE_MESSENGER = 'REQUESTED_INITIALIZE_MESSENGER';
export const INITIALIZED_MESSENGER_SUCESS = 'INITIALIZED_MESSENGER_SUCESS';
export const INITIALIZED_MESSENGER_FAILED = 'INITIALIZED_MESSENGER_FAILED';

/* Users */

export const REQUESTED_USERS = 'REQUESTED_USERS';
export const RECEIVED_USERS = 'RECEIVED_USERS';

/* Networks */

export const RECEIVED_NETWORKS = 'RECEIVED_NETWORKS';
